[[build.buildpacks]]
uri = "heroku/nodejs"

[[build.buildpacks]]
uri = "heroku/nodejs-yarn"

[[build.buildpacks]]
uri = "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest"

[[build.buildpacks]]
uri = "https://github.com/heroku/heroku-buildpack-chromedriver"
